customer: ""

azure_iot:
  hostname: "iothub-oor-ont-weu-itr-01.azure-devices.net"
  # hostname: "iothub-oor-prd-weu-ggi-01.azure-devices.net"
  device_id: "Luna"
  shared_access_key: "{SHARED_ACCESS_KEY_IOT}"

data_delivery_pipeline:
  detections_path: "/detections"
  metadata_path: "/temp_metadata"
  ml_model_id: "{ML_MODEL_ID}"
  project_version: "{PROJECT_VERSION}"
  sleep_time: 30

detection_pipeline:
  images_path: "/raw_frames"
  detections_path: "/detections"
  inference_params:
    img_size: 1280
    conf: 0.3
    save_img_flag: False
    save_txt_flag: False
    save_conf_flag: False
  model_name: "yolov8m_1280_v2.2_curious_hill_12.pt"
  pretrained_model_path: "/model_artifacts"
  defisheye_flag: True
  defisheye_params:
    camera_matrix: [[2028, 0, 1954.1], [0, 2029.6, 1055.1], [ 0, 0, 1]]
    distortion_params: [[-0.24083, 0.10647, 0.00083113, 0.0001802, -0.025874]]
    input_image_size: [3840, 2160]
  target_classes: [2]
  sensitive_classes: [0, 1]
  input_image_size: [3840, 2160]
  output_image_size: [1280, 720]  # null means keep original size
  target_classes_conf: 0.7  # 'null' means conf is taken from inference_params
  sensitive_classes_conf: null  # 'null' means conf is taken from inference_params
  skip_invalid_gps: True  # Whether or not to skip invalid GPS values
  acceptable_gps_delay: 5  # Acceptable delay in seconds, on inf to allow any delay
  sleep_time: 30
  training_mode: False
  training_mode_destination_path: "/training_mode"

logging:
  loglevel_own: DEBUG  # override loglevel for packages defined in `own_packages`
  own_packages: ["__main__", "oor_on_edge", "detection_pipeline", "data_delivery_pipeline", "performance_monitoring"]
  basic_config:
    # log config as arguments to `logging.basicConfig`
    level: WARNING
    format: "%(asctime)s|||%(levelname)-8s|%(name)s|%(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
  ai_instrumentation_key: "{AI_INSTRUMENTATION_KEY}"
  luna_logs_dir: "/cvt_logs"
